### ISSUE TITLE
Entangled blocks not working after server restart.

### ISSUE THREAD

**Issue by Robijnvogel** [TeacherGaming/qcraft-mod#6] opened 2016-01-13 12:00 UTC
Something I have observed, is that groups of entangled blocks seize to work after a server restart.

On a server I have crafted quantum blocks, entangled them and placed them.
After this I restarted and rejoined the server.
At first the blocks of the group seemed to be stuck in the state "in between states" (The green quantum animated texture) unable to decide what to become. After a few seconds they became completely invisible. They were still there though, as I could not replace them with other blocks.

The other quantum entangled blocks from the same group I had in my inventory could still be placed and worked as intended until another server restart.

EDIT
Actually, the same happens in single player if one exits and enters a game. This issue is not bound to servers.

In another 1.7.10 port of QubeSpace by OpenMC/VltsCraft entanglement and opening/closing a game also caused problems.
My guess is that it has something to do with the Entanglement registry not being saved or loaded properly, but I haven't quite been able to pinpoint it in the code.

Maybe the problem is the Entanglement registry being loaded after the Quantum Entangled blocks on world load?

**Comment by stanleyrya** [comment] 2016-02-18 19:37
Good news! I went back to a [previous commit](https://github.com/TeacherGaming/qcraft-mod/commit/26596cf1134029b2b563f5b363ee9eab3de880e0) and did some research. Here is what I found:

- New entangled blocks work as expected.
- Old entangled blocks (saved in the most [recent commit](https://github.com/TeacherGaming/qcraft-mod/commit/b799151f74a4b6a7124d4844933ab1a4a107366d)) have the same weird behavior as mentioned above. 

I can't promise a fast fix, but I want to further look into this today and make a pull request soon. Thanks for making the issue and posting online about the problem, that is what inspired me to look into it :)

**Comment by stanleyrya** [comment] 2016-02-18 20:08
Update:

I was able to narrow down the bug to the most [recent commit](https://github.com/TeacherGaming/qcraft-mod/commit/b799151f74a4b6a7124d4844933ab1a4a107366d). I'll continue to update whenever progress is made.

**Comment by stanleyrya** [comment] 2016-02-18 20:32
Update:

The most [recent commit](https://github.com/TeacherGaming/qcraft-mod/commit/b799151f74a4b6a7124d4844933ab1a4a107366d) also "breaks" blocks that were normal in older mod versions. It is unknown if you can get the blocks back to their original state, however it does not seem likely given that "broken" blocks do not resolve in older mod versions.

**Comment by stanleyrya** [comment] 2016-02-18 21:36
After doing some testing it seems as if the issue this commit intended to fix still remains. In the above-mentioned pull request I suggested removing this commit and opening up a new issue for the 'disentangled' quantum block bug. The issue is #8.

**Comment by Robijnvogel** [comment] 2016-02-19 06:20
That was the fix that I myself suggested XD
In Minecraft 1.7.2 this didn't cause extra issues though.
Do you have any other idea how to fix #8 without breaking other stuff?

**Comment by stanleyrya** [comment] 2016-02-19 06:27
Oh haha didn't even notice

Not sure, but I'd like to look into it :)

**Comment by kulttuuri** [comment] 2016-03-04 14:31
Any updates on this one?

**Comment by Robijnvogel** [comment] 2016-03-04 18:03
I hope so...
I noticed I misread some of the previous comments.
Right now, the question is: 
How to fix #6 and #9 , without causing the problems described in #8 .

**Comment by stanleyrya** [comment] 2016-03-04 18:07
I think the first step is to accept the pull request (#8) and remove the change that added this issue, afterwards I'm not sure how to tackle #9 yet :(

**Comment by stanleyrya** [comment] 2016-03-04 18:10
Has #9 caused any notable problems when playing with qCraft? As it doesn't break the system and does fix itself upon next observation, we may want to leave it as is, at least for now.

**Comment by Robijnvogel** [comment] 2016-03-04 20:09
It did not "fix itself upon next observation" before the fix that broke everything (#5). It actually became "disentagled" forever. I am willing to re-test this though.

I agree that reverting right now should be the first step though. My "fix" definitely broke more important things than it fixed.

So merge #8, close this issue and continue this conversation in #9?

**Comment by kulttuuri** [comment] 2016-03-06 18:26
Done! Merged revert back. Let's continue discussion in #9.

**Closed by kulttuuri** 2016-03-06 18:26 UTC
